name: Taiga-UI action for setup Cypress
description: Cypress

inputs:
  snapshot-path:
    description: Snapshot path
    required: true

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        echo "Provide cypress environments"
        echo "SNAPSHOTS_KEY=e2e-screenshots-${GITHUB_REF//\//-}-${GITHUB_SHA//\//-}" >> $GITHUB_ENV
        echo "SNAPSHOTS_PATH=${{ inputs.snapshot-path }}" >> $GITHUB_ENV

    - name: Show where is cypress cache
      shell: bash
      run: |
        npx cypress cache path
        npx cypress cache list
