name: 🤖 Auto approve by bot
on: pull_request

jobs:
  automated-pull-request:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if:
      github.actor == 'tinkoff-bot' && (contains(github.head_ref, 'release/') || contains(github.head_ref, 'renovate/'))
    steps:
      - uses: hmarr/auto-approve-action@v3.2.1
        with:
          review-message: 'LGTM (automated approve)'
