name: 🤖 Auto update bundled & used icons
on:
  pull_request:
  workflow_dispatch:

jobs:
  bundling:
    if: ${{ !contains(github.head_ref , 'release/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.67.3
      - uses: taiga-family/ci/actions/setup/variables@v1.67.3
      - uses: taiga-family/ci/actions/setup/node@v1.67.3
      - name: Lucide icons
        run: |
          npx nx prebuild icons
          npx nx build icons
      - name: Material icons
        run: |
          npx nx prebuild icons-material
          npx nx build icons-material
      - name: FontAwesome icons
        run: |
          npx nx prebuild icons-fontawesome
          npx nx build icons-fontawesome
      - run: |
          npx ts-node ./scripts/generate-used-icons.ts
          npx eslint ./projects/cdk/constants/used-icons.ts --fix || echo "no file matching"
          npx eslint ./projects/demo/used-icons.ts --fix || echo "no file matching"
          npx prettier ./projects/demo/used-icons.ts --write || echo "no file matching"
          npx prettier ./projects/cdk/constants/used-icons.ts --write || echo "no file matching"
      - uses: taiga-family/ci/actions/auto/push@v1.67.3
        with:
          message: icons have changed
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
