name: 🤖 Auto update bundled & used icons
on:
  pull_request:
  workflow_dispatch:

jobs:
  bundling:
    if: ${{ !contains(github.head_ref , 'release/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.0.0
      - uses: taiga-family/ci/actions/variables@1.12.5

      - uses: actions/checkout@v4.0.0
        if: env.SUPPORT_AUTO_PUSH == 'true'
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

      - uses: taiga-family/ci/actions/setup-node@1.12.5
      - run: |
          npx nx prebuild icons
          npx nx build icons

          npx ts-node ./scripts/generate-used-icons.ts
          npx eslint ./projects/cdk/constants/used-icons.ts --fix
          npx prettier ./projects/cdk/constants/used-icons.ts --write

      - name: Auto update bundled & used icons
        if: env.SUPPORT_AUTO_PUSH == 'true'
        uses: taiga-family/ci/actions/auto-push@1.12.5
        with:
          message: icons have changed
