name: Rebase onto main

on:
    push:
        branches: [main]

jobs:
    rebase:
        runs-on: ubuntu-latest
        steps:
            - name: Autorebase
              uses: peter-evans/rebase@v1.2.0
              with:
                  base: main
                  exclude-drafts: true
                  token: ${{ secrets.TINKOFF_BOT_PAT }}
                  exclude-labels: |
                      no-rebase
                      dependencies

concurrency:
    group: autorebase-${{ github.head_ref }}
    cancel-in-progress: true
