name: 🤖 Auto update bundled & used icons
on:
  pull_request:
  workflow_dispatch:

jobs:
  bundling:
    if: ${{ !contains(github.head_ref , 'release/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.25.8
      - uses: taiga-family/ci/actions/setup/variables@v1.25.8
      - uses: taiga-family/ci/actions/setup/checkout@v1.25.8
        if: env.SUPPORT_AUTO_PUSH == 'true'
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
      - uses: taiga-family/ci/actions/setup/node@v1.25.8
      - run: |
          npx nx prebuild icons
          npx nx build icons
          npx ts-node ./scripts/generate-used-icons.ts
          npx eslint ./projects/cdk/constants/used-icons.ts --fix
          npx prettier ./projects/cdk/constants/used-icons.ts --write
      - uses: taiga-family/ci/actions/auto/push@v1.25.8
        if: env.SUPPORT_AUTO_PUSH == 'true'
        with:
          message: icons have changed
