name: 🤖 Auto remove label on closed issue

on:
  issues:
    types: [closed]

jobs:
  remove_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: 'state: need triage'
