name: 🤖 Auto update dependencies by Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v36.0.3
        with:
          token: ${{ secrets.TINKOFF_BOT_PAT }}
          configurationFile: renovate.json
        env:
          LOG_LEVEL: 'debug'
