name: Rebase from v3.x branch

on:
  push:
    branches:
      - 'v3.x'

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - name: Autorebase from v3.x branch
        continue-on-error: true
        uses: peter-evans/rebase@v2
        with:
          base: v3.x
          token: ${{ secrets.TINKOFF_BOT_PAT }}
          head: 'Tinkoff:*'
          include-labels: 'v3.0 candidates'
