name: Rebase

on:
  push:
    branches: [main]

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - name: Autorebase
        continue-on-error: true
        uses: peter-evans/rebase@v2
        with:
          base: main
          token: ${{ secrets.TINKOFF_BOT_PAT }}
          head: 'Tinkoff:*' # skip rebase for fork branches
          exclude-labels: |
            no-rebase
            dependencies
          include-labels: |
            autorebase
