name: ⚙️ Build
on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    if: ${{ !contains(github.head_ref, 'release/') }}
    name: Build packages
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.44.4
      - uses: taiga-family/ci/actions/setup/variables@v1.44.4
      - uses: taiga-family/ci/actions/setup/node@v1.44.4
      - run: npm run run-many:build:libs
      - run: npx ts-node ./scripts/check-dist.ts

concurrency:
  group: build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
