name: ⚙️ Build

on:
  push:
    branches:
      - '!release/**'

env:
  NX_BRANCH: ${{ github.event.number }}
  NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}

jobs:
  build:
    name: Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - name: Run build libraries and check it
        run: |
          npm run run-many:build:libs
          npx ts-node ./scripts/check-dist.ts

concurrency:
  group: build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
