name: ⚙️ Build
on:
  pull_request:
  push:
    branches: [main]

jobs:
  libs:
    if: ${{ !contains(github.head_ref, 'release/') }}
    name: Build packages
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.55.18
      - uses: taiga-family/ci/actions/setup/variables@v1.55.18
      - uses: taiga-family/ci/actions/setup/node@v1.55.18
      - run: npm run run-many:build:libs
      - run: npx ts-node ./scripts/check-dist.ts

  demo:
    if: ${{ !contains(github.head_ref, 'release/') }}
    name: Prerender of demo application
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.55.18
      - uses: taiga-family/ci/actions/setup/variables@v1.55.18
      - uses: taiga-family/ci/actions/setup/node@v1.55.18
      - run: npx nx prerender demo
      - run: tree ${{ env.DIST }} -P '*.html'

concurrency:
  group: build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
