name: ⚙️ Build
on:
  pull_request:
  push:
    branches: [main]

jobs:
  libs:
    if: ${{ !contains(github.head_ref, 'release/') }}
    name: Build packages
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.60.1
      - uses: taiga-family/ci/actions/setup/variables@v1.60.1
      - uses: taiga-family/ci/actions/setup/node@v1.60.1
      - run: npm run run-many:build:libs
      - run: npx ts-node ./scripts/check-dist.ts

  demo:
    if: ${{ !contains(github.head_ref, 'release/') }}
    name: Prerender of demo application
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.60.1
      - uses: taiga-family/ci/actions/setup/variables@v1.60.1
      - uses: taiga-family/ci/actions/setup/node@v1.60.1
      - run: npx nx prerender demo
      - run: tree ${{ env.DIST }} -P '*.html'
      - name: Bundle size tracking
        run: npx --yes bundlemon --config .github/.bundlemonrc.json
        continue-on-error: true
        env:
          CI_COMMIT_SHA: ${{ env.CI_COMMIT_SHA }}

concurrency:
  group: build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
