name: ⚙️ Bundle size

on:
  push:
    branches:
      - '**'
      - '!release/**'

jobs:
  tracking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - run: npx nx build demo

      - name: Run BundleMon
        continue-on-error: true
        run: npx bundlemon
        env:
          CI_COMMIT_SHA: ${{github.event.pull_request.head.sha || github.sha}}
