name: ⚙️ Bundle size
on:
  push:
    branches: [main]
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  tracking:
    if: ${{ !contains(github.head_ref, 'release/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/variables@1.13.0
      - uses: actions/checkout@v4.1.0
      - uses: taiga-family/ci/actions/setup-node@1.13.0
      - run: npx nx build demo
      - name: Run BundleMon
        continue-on-error: true
        run: npx --yes bundlemon --config .github/.bundlemonrc.json
        env:
          CI_COMMIT_SHA: ${{ env.CI_COMMIT_SHA }}
