name: ⚙️ Bundle size
on:
  push:
    branches: [main]
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  tracking:
    if: ${{ !contains(github.head_ref, 'release/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.33.4
      - uses: taiga-family/ci/actions/setup/variables@v1.33.4
      - uses: taiga-family/ci/actions/setup/node@v1.33.4
      - run: npx nx build demo
      - run: npx --yes bundlemon --config .github/.bundlemonrc.json
        continue-on-error: true
        env:
          CI_COMMIT_SHA: ${{ env.CI_COMMIT_SHA }}
