name: Cleanup resources after close PR
on:
  pull_request:
    types: [closed]

jobs:
  purge-cache:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4.2.1
      - uses: taiga-family/ci/actions/setup/variables@v1.93.3
      - run: gh cache delete ${{ env.CACHE_DIST_KEY }}
        continue-on-error: true

  delete-firebase-channel:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4.2.1
      - uses: w9jds/firebase-action@v13.22.1
        continue-on-error: true
        with:
          args: hosting:channel:delete pr${{ github.event.number }}-${{ github.head_ref }} --force
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_TAIGA_PREVIEWS_SA }}
          PROJECT_ID: taiga-previews
