name: Create release

on:
  workflow_dispatch:
    inputs:
      mode:
        type: choice
        description: release type
        required: true
        default: 'minor'
        options:
          - patch
          - minor
          - major

jobs:
  run-release:
    name: Run release
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Fetch from origin repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          token: ${{ secrets.TINKOFF_BOT_PAT }}

      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - name: Run release
        id: run-release
        run: |
          git config user.name "tinkoff-bot"
          git config --global push.followTags true
          npm run exec -- ./scripts/release.ts --release-as ${{ github.event.inputs.mode }} --ci-mode

      - name: Generate Release Body
        id: generare_body
        run: |
          npx extract-changelog-release > RELEASE_BODY.md
          echo ::set-output name=tag_name::$(git describe HEAD --abbrev=0)

      - id: get-pr-body # The content must be escaped to preserve newlines.
        run: |
          body=$(cat RELEASE_BODY.md)
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}"
          echo ::set-output name=body::$body

      - name: Render template
        id: template
        uses: chuhlomin/render-template@v1.4
        with:
          template: .github/PULL_REQUEST_RELEASE_TEMPLATE.md
          vars: |
            RELEASE_BODY: ${{ steps.get-pr-body.outputs.body }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          delete-branch: true
          token: ${{ secrets.TINKOFF_BOT_PAT }}
          branch: release/${{ steps.run-release.outputs.new_version }}
          title: 'Release/${{ steps.run-release.outputs.new_version }}'
          body: ${{ steps.template.outputs.result }}

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          name: Release ${{ steps.generare_body.outputs.tag_name }}
          tag: ${{ steps.generare_body.outputs.tag_name }}
          bodyFile: 'RELEASE_BODY.md'
          token: ${{ secrets.GITHUB_TOKEN }}

concurrency:
  group: create-release-${{ github.head_ref }}
  cancel-in-progress: true
