name: Screenshot tests

on:
  pull_request:
    paths:
      - 'projects/**'
      - '!projects/*testing/**'
      - '!projects/demo/**'
      - '!projects/icons/**'
      - 'projects/demo/emulate/**'
      - 'angular.json'
      - 'package.json'
      - 'tsconfig*'
      - '**/demo-integrations.yml'
  push:
    branches:
      - '!main'
      - '!release/**'

env:
  NX_BRANCH: ${{ github.event.number }}
  CYPRESS_API_URL: http://localhost:1234/

  # disable shared memory X11 affecting Cypress v4 and Chrome
  # https://github.com/cypress-io/cypress-docker-images/issues/270
  QT_X11_NO_MITSHM: 1
  _X11_NO_MITSHM: 1
  _MITSHM: 0
  DISPLAY: ':99'

jobs:
  demo-integrations:
    name: Cypress
    runs-on: ubuntu-latest
    env:
      FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}

    services:
      sorry-cypress-director:
        image: agoldis/sorry-cypress-director:2.1
        ports:
          - 1234:1234

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 10

      - uses: imba-tjd/rebase-upstream-action@0.5
        continue-on-error: true
        with:
          upstream: Tinkoff/taiga-ui
          branch: main
          push: false

      - run: |
          sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - name: Ignore running parallel Xvfb servers
        run: Xvfb :99 &

      - name: Build demo/local application
        run: npm run build:demo

      - name: Serve demo/local application in background
        run: |
          npm run serve:compiled & sleep 5
          curl -X GET -I -f "http://localhost:3333"

      - name: Run screenshot tests on demo/localhost
        run: |
          npm run concurrently -- \
                             "npm run cy2:run:localhost" \
                             "npm run cy2:run:localhost" \
                             "npm run cy2:run:localhost"

      - name: Run screenshot tests on demo/next
        run: |
          npm run concurrently -- \
                         "npm run cy2:run:demo:next" \
                         "npm run cy2:run:demo:next" \
                         "npm run cy2:run:demo:next"

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: projects/demo-integrations/cypress/snapshots
          retention-days: 7

concurrency:
  group: demo-integrations-${{ github.head_ref }}
  cancel-in-progress: true
