name: Deploy / next

on:
  push:
    branches:
      - main
    paths:
      - 'projects/**'
      - 'angular.json'
      - 'package.json'
      - '**/deploy-next.yml'
  workflow_dispatch:

env:
  NX_BRANCH: ${{ github.event.number }}
  NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
  FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}

jobs:
  build-and-deploy:
    name: Next for branch ${{ github.head_ref || github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - run: npx nx build -c next

      - name: Deploy next from main branch to `taiga-ui.dev/next`
        if: ${{ github.ref_name == 'main' }}
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: dist/demo/browser/next
          target-folder: next
          token: ${{ secrets.TINKOFF_BOT_PAT }}
          silent: false

concurrency:
  group: deploy-next-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
