name: Deploy

on:
  push:
    branches:
      - 'release/**'
  workflow_dispatch:

env:
  NX_BRANCH: ${{ github.event.number }}

jobs:
  build-and-deploy:
    name: Demo
    runs-on: ubuntu-latest
    env:
      FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - run: npm run exec -- ./scripts/build-all-demo-snapshots.ts

      - name: Deploy # only from release branch
        if: ${{ contains(github.head_ref, 'release/') }}
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: dist/demo/browser
          token: ${{ secrets.TINKOFF_BOT_PAT }}
          silent: false
          clean: true
          clean-exclude: |
            CNAME

concurrency:
  group: deploy-${{ github.head_ref }}
  cancel-in-progress: true
