name: Deploy

on:
  push:
    branches:
      - 'release/**'
  workflow_dispatch:

env:
  NX_BRANCH: ${{ github.event.number }}

jobs:
  build-and-deploy:
    name: Demo
    runs-on: ubuntu-latest
    env:
      FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - run: |
          npm run build:demo
          npm run build:demo:next

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: dist/demo/browser
          token: ${{ secrets.TINKOFF_BOT_PAT }}
          git-config-name: ${{ github.event.pusher.name }}
          git-config-email: ${{ github.event.pusher.email }}
          commit-message: Artifacts from https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          single-commit: false
          silent: false

concurrency:
  group: deploy-${{ github.head_ref }}
  cancel-in-progress: true
