name: 🚀 Deploy / preview
on: pull_request

jobs:
  build_and_preview:
    if: ${{ !contains(github.head_ref, 'release/') }}
    name: Firebase
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.66.6
      - uses: taiga-family/ci/actions/setup/variables@v1.66.6
      - uses: taiga-family/ci/actions/setup/node@v1.66.6
      - run: npx nx build demo
      - name: Debug output
        run: tree dist/demo/browser -P '*.html'
      - name: Deploy preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        if: env.IS_OWNER_MODE == 'true'
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_TAIGA_PREVIEWS_SA }}
          projectId: taiga-previews
          expires: 1d

concurrency:
  group: firebase-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
