name: ⚙️ Playwright E2E

on:
  pull_request:

env:
  CACHE_DIST_KEY: dist-playwright-${{ github.head_ref }}-${{ github.ref }}-${{ github.sha }}
  BASE_REF_DEMO: dist/demo/browser/${{ github.base_ref }}
  LOCAL_REF_DEMO: dist/demo/browser
  NX_BRANCH: ${{ github.event.number }}
  NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
  NG_SERVER_PORT: 3333
  PLAYWRIGHT_SNAPSHOT_PATH: projects/demo-e2e/snapshots/__diff_output__

jobs:
  build-demo:
    if: ${{ !contains(github.head_ref , 'release/') }}
    name: Build demo # for reuse in e2e jobs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 10

      - name: Try rebase locally for check affected e2e
        uses: ./.github/actions/rebase
        continue-on-error: true

      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - name: Mark demo-app directory for persist in cache
        uses: actions/cache@v3
        with:
          path: dist/demo
          key: ${{ env.CACHE_DIST_KEY }}

      - name: Building demo-app of git-branch without cache
        run: npx nx build demo --skip-nx-cache -c next --output-path dist/demo/browser --base-href="/"

  playwright:
    if: ${{ !contains(github.head_ref , 'release/') }}
    needs: [build-demo]
    runs-on: ubuntu-latest
    env:
      max_parallel: 2
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2]
    name: shard / ${{ matrix.shard }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - name: Download ${{ env.LOCAL_REF_DEMO }} for serve locally
        uses: actions/cache@v3
        with:
          path: dist/demo
          key: ${{ env.CACHE_DIST_KEY }}

      - name: Serve ${{ env.LOCAL_REF_DEMO }} in background
        run: npx nx serve-compiled demo --path ${{ env.LOCAL_REF_DEMO }} --port ${{ env.NG_SERVER_PORT }}

      - name: Run screenshot tests on local
        run: |
          npx playwright test \
              --config projects/demo-e2e/playwright.config.ts \
              --project=chromium \
              --shard=${{ matrix.shard }}/${{ env.max_parallel }} \
              --update-snapshots

      - name: Clean up resources
        run: npx kill-port --port ${{ env.NG_SERVER_PORT }}

      - name: Download ${{ env.BASE_REF_DEMO }} for serve locally
        run: |
          git clone \
                --depth 1 \
                --branch snapshots/demo/next/${{ github.base_ref }} \
                https://github.com/Tinkoff/taiga-ui.git ${{ env.BASE_REF_DEMO }}

      - name: Find and replace baseHref for next snapshot
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: '<base href="./">'
          replace: '<base href="/">'
          include: '${{ env.BASE_REF_DEMO }}/index.html'
          regex: false

      - name: Serve ${{ env.BASE_REF_DEMO }} in background
        run: npx nx serve-compiled demo --path ${{ env.BASE_REF_DEMO }} --port ${{ env.NG_SERVER_PORT }}

      - name: Run screenshot tests on ${{ env.BASE_REF_DEMO }}
        run: |
          npx playwright test \
              --config projects/demo-e2e/playwright.config.ts \
              --shard=${{ matrix.shard }}/${{ env.max_parallel }} \
              --project=chromium

      - name: Clean up resources
        run: npx kill-port --port ${{ env.NG_SERVER_PORT }}

      - name: Check if diff-output exists
        id: diff-checker
        run: |
          echo "diff_exist=$(find ${{ env.PLAYWRIGHT_SNAPSHOT_PATH }} -regex '.*\.png$' | wc -l | sed -e 's/^[[:space:]]*//')" >> $GITHUB_OUTPUT

      - name: Fall with an error if diff-output exists
        if: ${{ steps.diff-checker.outputs.diff_exist != '0' }}
        run: |
          find ${{ env.PLAYWRIGHT_SNAPSHOT_PATH }} -regex '.*\.png$' -exec echo "{}" \;
          exit 1

      - name: Update artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          path: projects/demo-e2e/snapshots/
          name: ${{ env.SNAPSHOTS_E2E_KEY }}
          if-no-files-found: ignore
          retention-days: 1

concurrency:
  group: e2e-playwright-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
