name: ⚙️ Cypress component testing
on:
  push:
    branches:
      - '**'
      - '!release/*'

jobs:
  cypress:
    runs-on: ubuntu-latest
    name: Component testing result
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.51.14
      - uses: taiga-family/ci/actions/setup/variables@v1.51.14
      - uses: taiga-family/ci/actions/setup/node@v1.51.14
      - run: npx tsc -p projects/demo-cypress/tsconfig.json
      - run: npx nx component-test demo-cypress

concurrency:
  group: e2e-cypress-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
