name: ⚙️ Lint
on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    name: Lint
    if: ${{ !contains(github.head_ref, 'release/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.57.3
      - uses: taiga-family/ci/actions/setup/variables@v1.57.3
      - uses: taiga-family/ci/actions/setup/node@v1.57.3
      - run: npm run typecheck
      - run: npm run cspell -- --no-progress
      - run: |
          if [[ "${{ env.SUPPORT_AUTO_PUSH }}" == "true" ]]; then
              npm run prettier -- --write
              npm run stylelint -- --fix
              npm run lint -- --fix
          else
              npm run prettier -- --check
              npm run stylelint
              npm run lint
          fi
      - uses: taiga-family/ci/actions/auto/push@v1.57.3
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

concurrency:
  group: lint-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
