name: Lint

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main
            - '!release/**'

env:
    NX_BRANCH: ${{ github.event.number }}
    IS_FORK: ${{ github.event.pull_request.head.repo.full_name != github.repository }}
    IS_MAIN_BRANCH: ${{ github.ref == 'refs/heads/main' }}

jobs:
    lint:
        name: Format
        # Setup part
        runs-on: ubuntu-latest
        env:
            NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
        steps:
            - name: Fetch from origin repo
              if: ${{ env.IS_FORK == 'false' }}
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
                  token: ${{ secrets.TINKOFF_BOT_PAT }}
                  fetch-depth: 2
            - name: Fetch from forked repo
              if: ${{ env.IS_FORK == 'true' }}
              uses: actions/checkout@v2
              with:
                  fetch-depth: 2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
            - name: Cache Node.js modules
              uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.OS }}-node-
                      ${{ runner.OS }}-
            - name: Install dependencies
              run: npm ci
            # End of setup
            - name: Format
              run: |
                  npm run typecheck
                  npm run format:prettier
                  npm run format:tslint

            - name: Get last commit message
              if: ${{ env.IS_MAIN_BRANCH == 'false' && env.IS_FORK == 'false' }}
              id: last-commit-message
              run: |
                  git config user.name "tinkoff-bot"
                  echo "::set-output name=msg::$(git log -1 --pretty=%s)"

            - name: Apply changes after linting
              uses: stefanzweifel/git-auto-commit-action@v4.12.0
              if: ${{ env.IS_MAIN_BRANCH == 'false' && env.IS_FORK == 'false' }}
              with:
                  commit_message: ${{ steps.last-commit-message.outputs.msg }}
                  status_options: '--untracked-files=no'
                  commit_options: '--amend --no-edit --no-verify'
                  push_options: '--force-with-lease'
                  skip_fetch: true

concurrency:
    group: lint-${{ github.head_ref }}
    cancel-in-progress: true
