name: ⚙️ Lint
on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    if: ${{ !contains(github.head_ref, 'release/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - uses: taiga-family/ci/actions/setup/variables@v1.24.1
      - uses: actions/checkout@v4.1.0
        if: env.SUPPORT_AUTO_PUSH == 'true'
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
      - uses: taiga-family/ci/actions/setup/node@v1.24.1
      - run: npm run typecheck
      - run: npm run cspell -- --no-progress
      - run: npm run prettier ${{ env.SUPPORT_AUTO_PUSH == 'true' && '-- --write' || '-- --check' }}
      - run: npm run stylelint ${{ env.SUPPORT_AUTO_PUSH == 'true' && '-- --fix' || '' }}
      - run: npm run lint ${{ env.SUPPORT_AUTO_PUSH == 'true' && '-- --fix' || '' }}
      - name: Apply changes after linting
        if: env.SUPPORT_AUTO_PUSH == 'true'
        uses: taiga-family/ci/actions/auto/push@v1.24.1

concurrency:
  group: lint-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
