name: ⚠️ Publish Taiga UI packages
on:
  push:
    branches: ['release/*']

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: taiga-family/ci/actions/variables@1.7.5
      - uses: taiga-family/ci/actions/setup-node@1.7.5

      - name: Build publishable libraries
        run: npm run run-many:build:libs

      - name: Publish libraries
        run: npm run run-many:publish:libs

      - name: Get new version
        id: info
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Announce
        uses: taiga-family/ci/actions/announce@1.7.5
        with:
          version: ${{ steps.info.outputs.version }}
          url: ${{ secrets.ANNOUNCE_WEBHOOK }}
          channel: ${{ secrets.ANNOUNCE_TARGET }}

concurrency:
  group: release-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
