name: ⚠️ Publish canary management
on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * 1-5' # At UTC 20:00 (MSK 23:00) on every day-of-week from Monday through Friday

jobs:
  canary:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch: [v3.x, main]
    name: Publish canary for ${{ matrix.branch }} branch
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.71.0
        with:
          ref: ${{ matrix.branch }}
      - uses: taiga-family/ci/actions/setup/variables@v1.71.0
      - uses: taiga-family/ci/actions/setup/node@v1.71.0
        with:
          validate-peer-deps: 'false'
      - uses: taiga-family/ci/actions/setup/config/npm@v1.71.0
        with:
          token: ${{ secrets.TAIGA_UI_SCOPE_NPM_TOKEN }}
      - run: npm run run-many:build:libs
      - run: npx ts-node ./scripts/publish-canary.ts

concurrency:
  group: publish-canary-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
