name: ⚠️ Publish canary
on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * 1-5' # At UTC 20:00 (MSK 23:00) on every day-of-week from Monday through Friday

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  build:
    if: ${{ !contains(github.head_ref, 'release/') }}
    name: Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: taiga-family/ci/actions/variables@1.7.5
      - uses: taiga-family/ci/actions/setup-node@1.7.5
      - run: npx ts-node ./scripts/publish-canary.ts

concurrency:
  group: publish-canary-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
