name: ⚠️ Nightly publish
on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * 1-5' # At UTC 20:00 (MSK 23:00) on every day-of-week from Monday through Friday

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  build:
    if: ${{ !contains(github.head_ref, 'release/') }}
    name: Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - run: npm run run-many:build:libs

      - name: Publish dev builds
        run: npx ts-node ./scripts/publish-dev-builds.ts

concurrency:
  group: publish-dev-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
