name: Release Taiga UI packages

on:
  pull_request:
    types: [labeled]
    branches:
      - 'release/**'

env:
  NX_BRANCH: ${{ github.event.number }}
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}

jobs:
  build:
    if: ${{ github.event.label.name == 'ready to merge' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - name: Build publishable libraries
        run: npm run run-many:build:libs

      - name: Publish libraries
        run: npm run run-many:publish:libs

concurrency:
  group: release-${{ github.head_ref }}
  cancel-in-progress: true
