name: 🚀 Snapshots
on:
  push:
    # TODO: Revert this line before merge
    branches: [main, 'v[0-9]+.x', 'release/**', doc-base-href-v4]
  workflow_dispatch:
    inputs:
      updateMain:
        type: boolean
        required: false
        description: update main snapshots

jobs:
  next-snapshot:
    name: Push next snapshot
    if: ${{ !contains(github.head_ref || github.ref_name, 'release/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.66.6
      - uses: taiga-family/ci/actions/setup/variables@v1.66.6
      - uses: taiga-family/ci/actions/setup/node@v1.66.6

      - run: npx nx build demo
      - run: tree ${{ env.DIST }} -P '*.html'

      - uses: s0/git-publish-subdir-action@v2.6.0
        env:
          REPO: self
          FOLDER: ${{ env.DIST }}
          # TODO: Revert this line before merge
          BRANCH: snapshots/demo/next/main
          GITHUB_TOKEN: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

  production-snapshot:
    name: Push production snapshot
    # TODO: Revert this line before merge
    # if: ${{ contains(github.head_ref || github.ref_name, 'release/') || github.event.inputs.updateMain == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.66.6
      - uses: taiga-family/ci/actions/setup/variables@v1.66.6
      - uses: taiga-family/ci/actions/setup/node@v1.66.6
        id: nodejs-workspace

      - run: npx nx prerender demo
      - run: tree ${{ env.DIST }} -P '*.html'

      - uses: s0/git-publish-subdir-action@v2.6.0
        env:
          REPO: self
          FOLDER: ${{ env.DIST }}
          BRANCH: snapshots/demo/v${{ steps.nodejs-workspace.outputs.root-package-major-version }}.x
          GITHUB_TOKEN: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

concurrency:
  group: snapshots-${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true
