name: 🚀 Snapshots
on:
  push:
    branches: [main, 'v[0-9]+.x', 'release/**']
  workflow_dispatch:
    inputs:
      updateMain:
        type: boolean
        required: false
        description: update main snapshots

jobs:
  snapshots:
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.57.2
      - uses: taiga-family/ci/actions/setup/variables@v1.57.2
      - uses: taiga-family/ci/actions/setup/node@v1.57.2
      - run: npx nx build demo
      - run: tree ${{ env.DIST }} -P '*.html'

      - name: Publish next snapshots
        if: ${{ !contains(github.head_ref || github.ref_name, 'release/') }}
        uses: s0/git-publish-subdir-action@v2.6.0
        env:
          REPO: self
          FOLDER: ${{ env.DIST }}
          BRANCH: snapshots/demo/next/${{ github.head_ref || github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

      - name: Publish production snapshots
        if: ${{ contains(github.head_ref || github.ref_name, 'release/') || github.event.inputs.updateMain == 'true' }}
        uses: s0/git-publish-subdir-action@v2.6.0
        env:
          REPO: self
          FOLDER: ${{ env.DIST }}
          BRANCH: snapshots/demo/v${{ steps.nodejs-workspace.outputs.root-package-major-version }}.x
          GITHUB_TOKEN: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

concurrency:
  group: snapshots-${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true
