name: ⚙️ Unit tests

on:
  pull_request:
  push:
    branches:
      - main

env:
  NX_BRANCH: ${{ github.event.number }}
  NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
  FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
  IS_MAIN_BRANCH: ${{ github.ref == 'refs/heads/main' }}

jobs:
  test:
    if: ${{ !contains(github.head_ref, 'release/') }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project:
          [
            addon-charts,
            addon-commerce,
            addon-doc,
            addon-editor,
            addon-mobile,
            addon-preview,
            addon-table,
            addon-tablebars,
            cdk,
            core,
            demo,
            kit,
          ]
    name: ${{ matrix.project }}
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - name: Run tests for ${{ matrix.project }}
        run: npx nx test ${{ matrix.project }} --skip-nx-cache

      - name: Display structure of coverage files
        if: ${{ !contains(matrix.project, 'demo') }}
        run: tree -L 2 ./coverage -P 'lcov.info'

      - name: Generate coverage report
        if: ${{ !contains(matrix.project, 'demo') }}
        uses: codecov/codecov-action@v3.1.3
        with:
          directory: ./coverage/${{ matrix.project }}/
          flags: summary,${{ matrix.project }}
          name: ${{ matrix.project }}
          verbose: true

concurrency:
  group: test-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
