name: ⚙️ Unit tests
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    if: ${{ !contains(github.head_ref, 'release/') }}
    runs-on: ubuntu-latest
    name: Unit tests
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.50.8
      - uses: taiga-family/ci/actions/setup/variables@v1.50.8
      - uses: taiga-family/ci/actions/setup/node@v1.50.8
      - run: npx nx run-many -t test --output-style=stream
      - run: tree -L 2 ./coverage -P 'lcov.info'
      - uses: codecov/codecov-action@v3.1.5
        with:
          directory: ./coverage/
          flags: summary
          name: units

concurrency:
  group: test-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
