name: PR for main branch from v2.x

on:
  push:
    branches:
      - v2.x

jobs:
  cherry-pick-pull-request:
    runs-on: ubuntu-latest
    name: cherry-pick-pull-request
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Cherry pick into main
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.1
        with:
          branch: main
          token: ${{ secrets.TINKOFF_BOT_PAT }}
          labels: cherry-pick-v2.x
